### ISSUE TITLE
劳驾请教一下，什么时候出客户端呀？macOS&iOS ？

### ISSUE THREAD

**Issue by yehon** [LIU9293/musicafe#1]
如题；
感谢开发者的付出，让人们可以有这么便利的工具。

**Comment by LIU9293** [comment]
我的确在做客户端，用RN。不过我没有什么原生的APP开发经验，所以遇到一些问题解决起来比较慢，所以可能不会太快，估计IOS会先出来吧。

**Comment by yehon** [comment]
如果你有时间，可以联系 guodong000[at]gmail.com 交流，他是我兄弟，会客户端开发。我本职是产品经理，如果你想打算做 macOS 端，我们可以一起聊聊产品构思什么的。

**Comment by LIU9293** [comment]
多谢支持，暂时没打算MacOS，一个人精力也比较有限，有什么感兴趣的可以加我微信: liukai730219

**Comment by yehon** [comment]
嗯，常联系。
