### ISSUE TITLE
npm run https error

### ISSUE THREAD

**Issue by and0rw** [LIU9293/musicafe#2]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Shinelon\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "https"
npm ERR! node v7.5.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! music@0.1.0 https: `HTTPS=true npm start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the music@0.1.0 https script 'HTTPS=true npm start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the music package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     HTTPS=true npm start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs music
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls music
npm ERR! There is likely additional logging output above.

**Comment by LIU9293** [comment]
hi, seems you are using windows, on windows we need maybe `set HTTPS=true npm start`, or you can refer to create-react-app doc to see how to use https in windows.

**Comment by LIU9293** [comment]
No longer useful as the start config changes now.
