### ISSUE TITLE
大佬的iOS版本不打算发布了吗？

### ISSUE THREAD

**Issue by learnsss** [LIU9293/musicafe#3]
在iOS上听歌太费劲了，而且大佬网站关闭后听歌感觉更加费劲，不然大佬发个tf让我们尝尝鲜😂😂

**Comment by LIU9293** [comment]
https://github.com/LIU9293/musicafe-app
这个IOS的应该可以跑起来，我已经听了蛮久的了，但还是有不少bug
而且这个项目应该不打算维护了，想想毕竟是有版权风险，以后想转向音乐可视化

**Comment by learnsss** [comment]
@LIU9293 大佬，表示研究不懂怎么用,,ԾㅂԾ,,
